import {
  Account,
  Call,
  Campaign,
  Contact,
  Deal,
  Lead,
  LoanFacility,
  Meeting,
  ModuleKey,
  Task,
  TimelineEvent,
  WorkflowRule,
} from "./types";

export const modules: Array<{
  key: Exclude<ModuleKey, "home" | "reports">;
  label: string;
  /** Full name shown on hover when label is abbreviated. */
  title?: string;
}> = [
  { key: "accounts", label: "Clients" },
  { key: "contacts", label: "Contacts" },
  { key: "deals", label: "Loans" },
  {
    key: "tradeFinance",
    label: "GTS",
    title: "Global Trade Solutions",
  },
  {
    key: "paymentService",
    label: "GPS",
    title: "Global Payment Service",
  },
  {
    key: "sustainableFinance",
    label: "SF",
    title: "Sustainable Finance",
  },
  {
    key: "globalMarket",
    label: "GM",
    title: "Global Market",
  },
  { key: "lifeInsurance", label: "Life Insurance" },
  { key: "campaigns", label: "Event Trigger" },
  { key: "tasks", label: "Tasks" },
  { key: "meetings", label: "Meetings" },
  { key: "calls", label: "Calls" },
];

export const leads: Lead[] = [
  {
    id: "lead-1",
    name: "Christopher Maclead (Sample)",
    company: "Rangoni Of Florence",
    email: "christopher-maclead@noemail.invalid",
    phone: "555-555-5555",
    owner: "Jenny",
    status: "New",
  },
  {
    id: "lead-2",
    name: "Carissa Kidman (Sample)",
    company: "Oh My Goodknits Inc",
    email: "carissa-kidman@noemail.invalid",
    phone: "555-555-5555",
    owner: "Jenny",
    tag: "Today",
    status: "Contacted",
  },
  {
    id: "lead-3",
    name: "James Merced (Sample)",
    company: "Kwik Kopy Printing",
    email: "james-merced@noemail.invalid",
    phone: "555-555-5555",
    owner: "Jenny",
    status: "Qualified",
  },
  {
    id: "lead-4",
    name: "Tresa Sweely (Sample)",
    company: "Morlong Associates",
    email: "tresa-sweely@noemail.invalid",
    phone: "555-555-5555",
    owner: "Jenny",
    status: "New",
  },
  {
    id: "lead-5",
    name: "Michael Ruta (Sample)",
    company: "Buckley Miller & Wright",
    email: "michael-gruta@noemail.invalid",
    phone: "555-555-5555",
    owner: "Jenny",
    tag: "Jul 31",
    status: "Converted",
  },
];

export const accounts: Account[] = [
  {
    id: "acc-1",
    companyName: "King (Sample)",
    status: "Active",
    clientStatus: "ETB",
    relationshipManager: "Jenny",
    phone: "555-555-1001",
    phone2: "",
    email: "treasury@king-sample.com",
    website: "https://king-sample.com",
    sicCode: "3711",
    industry: "Manufacturing",
    creIndicator: true,
    countryRegionCampaignCode: "HK-CAM-2024-01",
    referralDate: "2024-01-15",
    existingClientReferral: true,
    hacnBuddyingRegionBranch: "HACN Hong Kong / Central",
    rating: "Hot",
    segment: "Corporate",
    riskRating: "Medium",
    kycStatus: "Approved",
    region: "Hong Kong",
    legalEntityType: "Limited Company",
    country: "Hong Kong",
    city: "Central",
    address: "18 Queen's Road Central, 22F",
    annualRevenue: "HKD 1.2B",
    employeeCount: "4,800",
    creditLimit: "HKD 80M",
    clientSince: "2018-03-12",
    parentGroup: "King Holdings",
    primaryIdType: "BR Number",
    primaryIdNumber: "BR-100245",
    productsOfInterest: ["Loans", "Trade Finance", "Cash Management"],
    preferredChannels: ["Email", "In-Person"],
  },
  {
    id: "acc-2",
    companyName: "Truhlar And Truhlar (Sample)",
    status: "Active",
    clientStatus: "NTB",
    relationshipManager: "Donna",
    phone: "555-555-1002",
    phone2: "",
    email: "partners@truhlar.com",
    website: "https://truhlar.com",
    sicCode: "8111",
    industry: "Professional Services",
    creIndicator: false,
    countryRegionCampaignCode: "SG-REF-2025-08",
    referralDate: "2025-08-02",
    existingClientReferral: false,
    hacnBuddyingRegionBranch: "HACN Singapore / Orchard",
    rating: "Warm",
    segment: "Commercial",
    riskRating: "Low",
    kycStatus: "In Progress",
    region: "Singapore",
    legalEntityType: "Partnership",
    country: "Singapore",
    city: "Downtown Core",
    address: "1 Raffles Place, #18-01",
    annualRevenue: "SGD 86M",
    employeeCount: "320",
    creditLimit: "SGD 12M",
    clientSince: "2025-11-02",
    parentGroup: "",
    primaryIdType: "Type X",
    primaryIdNumber: "TX-88421",
    productsOfInterest: ["Loans", "Payments"],
    preferredChannels: ["Phone", "Email"],
  },
  {
    id: "acc-3",
    companyName: "Commercial Press (Sample)",
    status: "Inactive",
    clientStatus: "NNTB",
    relationshipManager: "James",
    phone: "555-555-1003",
    phone2: "",
    email: "finance@commercialpress.com",
    website: "https://commercialpress.com",
    sicCode: "2752",
    industry: "Retail & Consumer",
    creIndicator: true,
    countryRegionCampaignCode: "HK-CRE-2023-11",
    referralDate: "2023-11-20",
    existingClientReferral: true,
    hacnBuddyingRegionBranch: "HACN Hong Kong / Kowloon",
    rating: "Cold",
    segment: "SME",
    riskRating: "High",
    kycStatus: "Pending",
    region: "Mainland China",
    legalEntityType: "Limited Company",
    country: "China",
    city: "Shanghai",
    address: "888 Century Avenue, Pudong",
    annualRevenue: "CNY 210M",
    employeeCount: "1,150",
    creditLimit: "CNY 25M",
    clientSince: "2026-06-18",
    parentGroup: "Press Media Group",
    primaryIdType: "C Number",
    primaryIdNumber: "C-55201",
    productsOfInterest: ["Loans"],
    preferredChannels: ["Email"],
  },
  {
    id: "acc-4",
    companyName: "Morlong Associates (Sample)",
    status: "Active",
    clientStatus: "ETB",
    relationshipManager: "Jenny",
    phone: "555-555-1004",
    phone2: "",
    email: "rm@morlong.com",
    website: "https://morlong.com",
    sicCode: "6021",
    industry: "Banking & Financial Services",
    creIndicator: false,
    countryRegionCampaignCode: "HK-CAM-2022-04",
    referralDate: "2022-04-10",
    existingClientReferral: false,
    hacnBuddyingRegionBranch: "HACN Hong Kong / Admiralty",
    rating: "Hot",
    segment: "Corporate",
    riskRating: "Low",
    kycStatus: "Approved",
    region: "Hong Kong",
    legalEntityType: "Listed Company",
    country: "Hong Kong",
    city: "Admiralty",
    address: "Two International Finance Centre, 38F",
    annualRevenue: "HKD 3.4B",
    employeeCount: "2,200",
    creditLimit: "HKD 150M",
    clientSince: "2014-09-08",
    parentGroup: "Morlong Group",
    primaryIdType: "BR Number",
    primaryIdNumber: "BR-100892",
    productsOfInterest: ["Loans", "Trade Finance", "FX / Global Markets", "Sustainable Finance"],
    preferredChannels: ["Email", "In-Person", "WeChat / Instant Message"],
  },
  {
    id: "acc-5",
    companyName: "Pacific Logistics Hub",
    status: "Active",
    clientStatus: "ETB",
    relationshipManager: "Mitsu",
    phone: "852-3120-8800",
    phone2: "",
    email: "treasury@pacificlogistics.hk",
    website: "https://pacificlogistics.hk",
    sicCode: "4213",
    industry: "Transportation & Logistics",
    creIndicator: true,
    countryRegionCampaignCode: "APAC-LOG-2020-01",
    referralDate: "2020-01-08",
    existingClientReferral: true,
    hacnBuddyingRegionBranch: "HACN Hong Kong / Kwai Chung",
    rating: "Warm",
    segment: "Commercial",
    riskRating: "Medium",
    kycStatus: "Approved",
    region: "Asia Pacific",
    legalEntityType: "Limited Company",
    country: "Hong Kong",
    city: "Kwai Chung",
    address: "Container Terminal 9, Tower A",
    annualRevenue: "HKD 640M",
    employeeCount: "980",
    creditLimit: "HKD 45M",
    clientSince: "2020-01-21",
    parentGroup: "Pacific Trade Consortium",
    primaryIdType: "BR Number",
    primaryIdNumber: "BR-220417",
    productsOfInterest: ["Trade Finance", "Payments", "Cash Management"],
    preferredChannels: ["Phone", "Mobile", "Email"],
  },
  {
    id: "acc-6",
    companyName: "Aurora Health Systems",
    status: "Active",
    clientStatus: "NTB",
    relationshipManager: "Leota",
    phone: "65-6808-2299",
    phone2: "",
    email: "cfo@aurorahealth.sg",
    website: "https://aurorahealth.sg",
    sicCode: "8062",
    industry: "Healthcare",
    creIndicator: false,
    countryRegionCampaignCode: "SG-HEALTH-2026-02",
    referralDate: "2026-02-01",
    existingClientReferral: false,
    hacnBuddyingRegionBranch: "HACN Singapore / Novena",
    rating: "Hot",
    segment: "Corporate",
    riskRating: "Low",
    kycStatus: "In Progress",
    region: "Singapore",
    legalEntityType: "Listed Company",
    country: "Singapore",
    city: "Novena",
    address: "10 Sinaran Drive, #12-01",
    annualRevenue: "SGD 1.1B",
    employeeCount: "6,400",
    creditLimit: "SGD 90M",
    clientSince: "2026-02-14",
    parentGroup: "Aurora International",
    primaryIdType: "Type X",
    primaryIdNumber: "TX-99102",
    productsOfInterest: ["Loans", "Life Insurance", "Wealth Management"],
    preferredChannels: ["Email", "In-Person"],
  },
  {
    id: "acc-7",
    companyName: "NovaTech Solutions",
    status: "Inactive",
    clientStatus: "NNTB",
    relationshipManager: "Donna",
    phone: "852-2501-6677",
    phone2: "",
    email: "billing@novatech.io",
    website: "https://novatech.io",
    sicCode: "7372",
    industry: "Technology",
    creIndicator: false,
    countryRegionCampaignCode: "HK-TECH-2026-07",
    referralDate: "2026-06-18",
    existingClientReferral: false,
    hacnBuddyingRegionBranch: "HACN Hong Kong / Science Park",
    rating: "Warm",
    segment: "SME",
    riskRating: "Medium",
    kycStatus: "Pending",
    region: "Hong Kong",
    legalEntityType: "Limited Company",
    country: "Hong Kong",
    city: "Science Park",
    address: "Hong Kong Science Park, Building 15W",
    annualRevenue: "HKD 95M",
    employeeCount: "210",
    creditLimit: "HKD 8M",
    clientSince: "2026-07-01",
    parentGroup: "",
    primaryIdType: "C Number",
    primaryIdNumber: "C-77830",
    productsOfInterest: ["Payments", "Cash Management"],
    preferredChannels: ["Mobile", "WeChat / Instant Message"],
  },
  {
    id: "acc-8",
    companyName: "Sterling Private Office",
    status: "Active",
    clientStatus: "ETB",
    relationshipManager: "Jenny",
    phone: "44-20-7946-0812",
    phone2: "",
    email: "office@sterlingprivate.com",
    website: "https://sterlingprivate.com",
    sicCode: "6282",
    industry: "Banking & Financial Services",
    creIndicator: true,
    countryRegionCampaignCode: "EU-PB-2016-05",
    referralDate: "2016-05-12",
    existingClientReferral: true,
    hacnBuddyingRegionBranch: "HACN Europe / London",
    rating: "Hot",
    segment: "Private Banking",
    riskRating: "Low",
    kycStatus: "Approved",
    region: "Europe",
    legalEntityType: "Branch",
    country: "United Kingdom",
    city: "London",
    address: "1 Mayfair Place, Suite 4",
    annualRevenue: "GBP 420M",
    employeeCount: "85",
    creditLimit: "GBP 60M",
    clientSince: "2016-05-30",
    parentGroup: "Sterling Family Trust",
    primaryIdType: "Type X",
    primaryIdNumber: "TX-33018",
    productsOfInterest: ["Wealth Management", "Life Insurance", "FX / Global Markets"],
    preferredChannels: ["In-Person", "Email", "Phone"],
  },
];

export const contacts: Contact[] = [
  {
    id: "con-1",
    name: "Art Venere (Sample)",
    title: "Group Treasurer",
    department: "Treasury",
    accountId: "acc-1",
    account: "King (Sample)",
    email: "art.venere@king-sample.com",
    phone: "852-2555-1001",
    mobile: "852-9123-1001",
    owner: "Jenny",
    status: "Active",
    role: "Primary Contact",
    preferredChannel: "Email",
    region: "Hong Kong",
    decisionMaker: true,
    lastContacted: "2026-07-25",
    notes: "Primary counterparty for King Facility Renewal; prefers afternoon calls.",
  },
  {
    id: "con-2",
    name: "Sage Wieser (Sample)",
    title: "Managing Partner",
    department: "Partnership",
    accountId: "acc-2",
    account: "Truhlar And Truhlar (Sample)",
    email: "sage.wieser@truhlar.com",
    phone: "65-6555-1002",
    mobile: "65-8123-1002",
    owner: "Donna",
    status: "Active",
    role: "Decision Maker",
    preferredChannel: "Phone",
    region: "Singapore",
    decisionMaker: true,
    lastContacted: "2026-07-18",
    notes: "NTB commercial law firm contact for first RCF discussion.",
  },
  {
    id: "con-3",
    name: "Josephine Darakjy (Sample)",
    title: "Finance Director",
    department: "Finance",
    accountId: "acc-3",
    account: "Commercial Press (Sample)",
    email: "josephine.darakjy@commercialpress.com",
    phone: "86-21-5555-1003",
    mobile: "86-139-5555-1003",
    owner: "James",
    status: "Active",
    role: "CFO / Finance",
    preferredChannel: "WeChat / Instant Message",
    region: "Mainland China",
    decisionMaker: false,
    lastContacted: "2026-07-20",
    notes: "Capex term loan inquiry; KYC pack still outstanding.",
  },
  {
    id: "con-4",
    name: "James Venere (Sample)",
    title: "Head of Trade Finance",
    department: "Trade",
    accountId: "acc-4",
    account: "Morlong Associates (Sample)",
    email: "james.venere@morlong.com",
    phone: "852-2555-1004",
    mobile: "852-9123-1004",
    owner: "Jenny",
    status: "Active",
    role: "Treasury",
    preferredChannel: "Email",
    region: "Hong Kong",
    decisionMaker: true,
    lastContacted: "2026-07-28",
    notes: "Trade line primary contact; coordinates LC/TR utilization with club banks.",
  },
  {
    id: "con-5",
    name: "Lenna Paprocki (Sample)",
    title: "CFO",
    department: "Finance",
    accountId: "acc-5",
    account: "Pacific Logistics Hub",
    email: "lenna.paprocki@pacificlogistics.hk",
    phone: "852-3120-8801",
    mobile: "852-9188-8801",
    owner: "Mitsu",
    status: "Active",
    role: "CFO / Finance",
    preferredChannel: "In-Person",
    region: "Asia Pacific",
    decisionMaker: true,
    lastContacted: "2026-07-24",
    notes: "Fleet expansion loan sponsor; available for site visit at Kwai Chung.",
  },
  {
    id: "con-6",
    name: "Leota Dilliard (Sample)",
    title: "Chief Financial Officer",
    department: "Corporate Finance",
    accountId: "acc-6",
    account: "Aurora Health Systems",
    email: "leota.dilliard@aurorahealth.sg",
    phone: "65-6808-2299",
    mobile: "65-9012-2299",
    owner: "Leota",
    status: "Active",
    role: "Primary Contact",
    preferredChannel: "Email",
    region: "Singapore",
    decisionMaker: true,
    lastContacted: "2026-07-15",
    notes: "Hospital capex facility; awaiting first drawdown documentation.",
  },
  {
    id: "con-7",
    name: "Donette Foller (Sample)",
    title: "Founder & CEO",
    department: "Executive",
    accountId: "acc-7",
    account: "NovaTech Solutions",
    email: "donette.foller@novatech.io",
    phone: "852-2501-6677",
    mobile: "852-6221-6677",
    owner: "Donna",
    status: "Inactive",
    role: "Decision Maker",
    preferredChannel: "Mobile",
    region: "Hong Kong",
    decisionMaker: true,
    lastContacted: "2026-07-01",
    notes: "Account inactive pending KYC; OD facility remains in pipeline.",
  },
  {
    id: "con-8",
    name: "Simona Morasca (Sample)",
    title: "Family Office Principal",
    department: "Private Office",
    accountId: "acc-8",
    account: "Sterling Private Office",
    email: "simona.morasca@sterlingprivate.com",
    phone: "44-20-7946-0812",
    mobile: "44-7700-900812",
    owner: "Jenny",
    status: "Active",
    role: "Decision Maker",
    preferredChannel: "In-Person",
    region: "Europe",
    decisionMaker: true,
    lastContacted: "2026-07-22",
    notes: "Mortgage portfolio contact; prefers Mayfair meetings over calls.",
  },
  {
    id: "con-9",
    name: "Kiley Caldarera (Sample)",
    title: "Compliance Manager",
    department: "Legal & Compliance",
    accountId: "acc-1",
    account: "King (Sample)",
    email: "kiley.caldarera@king-sample.com",
    phone: "852-2555-1011",
    mobile: "852-9123-1011",
    owner: "Jenny",
    status: "Active",
    role: "Legal / Compliance",
    preferredChannel: "Email",
    region: "Hong Kong",
    decisionMaker: false,
    lastContacted: "2026-07-10",
    notes: "Handles KYC refresh and facility documentation for King group.",
  },
  {
    id: "con-10",
    name: "Abel Maclead (Sample)",
    title: "Operations Director",
    department: "Operations",
    accountId: "acc-5",
    account: "Pacific Logistics Hub",
    email: "abel.maclead@pacificlogistics.hk",
    phone: "852-3120-8810",
    mobile: "852-9188-8810",
    owner: "Mitsu",
    status: "Active",
    role: "Operations",
    preferredChannel: "Phone",
    region: "Asia Pacific",
    decisionMaker: false,
    lastContacted: "2026-07-12",
    notes: "Operational contact for collateral inspections and fleet schedules.",
  },
];

export const tasks: Task[] = [
  { id: "task-1", subject: "Register for upcoming CRM Webinars", dueDate: "2026-07-30", status: "Not Started", priority: "High", account: "King (Sample)" },
  { id: "task-2", subject: "Follow up with Rangoni Of Florence", dueDate: "2026-07-30", status: "Not Started", priority: "Normal", account: "Rangoni Of Florence" },
  { id: "task-3", subject: "Prepare Q3 pipeline review", dueDate: "2026-07-29", status: "Completed", priority: "High", account: "Commercial Press (Sample)" },
  { id: "task-4", subject: "Send contract draft to Morlong", dueDate: "2026-07-28", status: "Not Started", priority: "High", account: "Morlong Associates (Sample)" },
  { id: "task-5", subject: "Update lead scoring rules", dueDate: "2026-07-31", status: "Deferred", priority: "Low", account: "King (Sample)" },
  { id: "task-6", subject: "Confirm TradeShow booth setup", dueDate: "2026-08-01", status: "Not Started", priority: "Normal", account: "Chemel" },
  { id: "task-7", subject: "Review webinar registration list", dueDate: "2026-07-25", status: "Completed", priority: "Normal", account: "King (Sample)" },
  { id: "task-8", subject: "Schedule discovery call", dueDate: "2026-08-03", status: "Not Started", priority: "High", account: "Truhlar And Truhlar (Sample)" },
  { id: "task-9", subject: "Upload signed NDA", dueDate: "2026-07-22", status: "Completed", priority: "Low", account: "Buckley Miller & Wright" },
  { id: "task-10", subject: "Refresh campaign landing page", dueDate: "2026-08-05", status: "Not Started", priority: "Normal", account: "King (Sample)" },
];

export const meetings: Meeting[] = [
  { id: "meeting-1", title: "Demo", from: "2026-07-28 06:16 PM", to: "2026-07-28 07:16 PM", relatedTo: "Printing Dimensions", owner: "Donna" },
  { id: "meeting-2", title: "Webinar", from: "2026-07-28 08:16 PM", to: "2026-07-28 09:16 PM", relatedTo: "Commercial Press (Sample)", owner: "Leota" },
  { id: "meeting-3", title: "TradeShow", from: "2026-07-28", to: "2026-07-28", relatedTo: "Chemel", owner: "James" },
  { id: "meeting-4", title: "Seminar", from: "2026-07-30 10:00 AM", to: "2026-07-30 11:30 AM", relatedTo: "Carissa Kidman (Sample)", owner: "Jenny" },
  { id: "meeting-5", title: "CRM Webinar", from: "2026-07-30 02:00 PM", to: "2026-07-30 03:00 PM", relatedTo: "Morlong Associates", owner: "Mitsu" },
  { id: "meeting-6", title: "Client Kickoff", from: "2026-07-31 09:00 AM", to: "2026-07-31 10:00 AM", relatedTo: "King (Sample)", owner: "Jenny" },
  { id: "meeting-7", title: "Pipeline Sync", from: "2026-08-01 03:00 PM", to: "2026-08-01 04:00 PM", relatedTo: "Truhlar And Truhlar (Sample)", owner: "Donna" },
];

export const calls: Call[] = [
  { id: "call-1", subject: "Outgoing call to Leota Dilliard (Sample)", type: "Outbound", startTime: "2026-07-28 03:14 PM", duration: "00:00" },
  { id: "call-2", subject: "Call Customer on Potential", type: "Inbound", startTime: "2026-07-28 12:16 PM", duration: "00:15" },
  { id: "call-3", subject: "Follow up with Lead", type: "Outbound", startTime: "2026-07-28 04:16 PM", duration: "00:30" },
];

export const deals: Deal[] = [
  {
    id: "deal-1",
    name: "King Facility Renewal",
    facilityNumber: "LN-2026-001",
    accountId: "acc-1",
    account: "King (Sample)",
    contact: "Art Venere (Sample)",
    owner: "Jenny",
    businessUnit: "Corporate Banking",
    bookingBranch: "HK Central Corporate",
    productType: "Revolving Credit",
    purpose: "Refinancing",
    currency: "HKD",
    amount: 32000000,
    approvedAmount: 30000000,
    outstandingBalance: 21800000,
    tenorMonths: 36,
    repaymentFrequency: "Quarterly",
    rateType: "Floating",
    interestRate: 4.75,
    benchmarkRate: "HIBOR 3M",
    spreadBps: 125,
    arrangementFeeBps: 40,
    commitmentFeeBps: 35,
    utilizationPct: 73,
    collateralType: "Property",
    collateralValue: 50000000,
    ltv: 60,
    guarantor: "King Holdings",
    riskGrade: "Medium",
    internalRating: "BBB+",
    facilityStatus: "Drawn",
    approvalAuthority: "Credit Committee",
    syndicated: false,
    applicationDate: "2026-06-28",
    approvalDate: "2026-07-22",
    drawdownDate: "2026-07-25",
    maturityDate: "2029-07-31",
    closingDate: "2026-07-31",
    nextReviewDate: "2026-07-15",
    stage: "Execution",
    probability: 75,
    remarks: "Annual renewal of working capital RCF for manufacturing group treasury.",
    updatedAt: "2026-06-12T09:00:00.000Z",
  },
  {
    id: "deal-2",
    name: "Truhlar Working Capital RCF",
    facilityNumber: "LN-2026-002",
    accountId: "acc-2",
    account: "Truhlar And Truhlar (Sample)",
    contact: "Sage Wieser (Sample)",
    owner: "Donna",
    businessUnit: "Commercial Banking",
    bookingBranch: "SG Downtown Commercial",
    productType: "Revolving Credit",
    purpose: "Working Capital",
    currency: "SGD",
    amount: 4500000,
    approvedAmount: 0,
    outstandingBalance: 0,
    tenorMonths: 24,
    repaymentFrequency: "Quarterly",
    rateType: "Floating",
    interestRate: 4.1,
    benchmarkRate: "SORA 3M",
    spreadBps: 90,
    arrangementFeeBps: 25,
    commitmentFeeBps: 30,
    utilizationPct: 0,
    collateralType: "Guarantee",
    collateralValue: 6000000,
    ltv: 75,
    guarantor: "Truhlar Partners",
    riskGrade: "Low",
    internalRating: "A-",
    facilityStatus: "Pipeline",
    approvalAuthority: "Regional Credit",
    syndicated: false,
    applicationDate: "2026-07-18",
    approvalDate: "",
    drawdownDate: "",
    maturityDate: "2028-07-29",
    closingDate: "2026-07-29",
    nextReviewDate: "",
    stage: "Evaluation",
    probability: 25,
    remarks: "NTB commercial law firm seeking first RCF with bank guarantee support.",
    updatedAt: "2026-07-25T10:00:00.000Z",
  },
  {
    id: "deal-3",
    name: "Commercial Press Capex Term Loan",
    facilityNumber: "LN-2026-003",
    accountId: "acc-3",
    account: "Commercial Press (Sample)",
    contact: "Josephine Darakjy (Sample)",
    owner: "James",
    businessUnit: "SME Banking",
    bookingBranch: "SH Pudong SME",
    productType: "Term Loan",
    purpose: "Asset Purchase",
    currency: "CNY",
    amount: 18000000,
    approvedAmount: 0,
    outstandingBalance: 0,
    tenorMonths: 48,
    repaymentFrequency: "Monthly",
    rateType: "Floating",
    interestRate: 4.6,
    benchmarkRate: "LPR 1Y",
    spreadBps: 110,
    arrangementFeeBps: 50,
    commitmentFeeBps: 0,
    utilizationPct: 0,
    collateralType: "Unsecured",
    collateralValue: 0,
    ltv: 0,
    guarantor: "",
    riskGrade: "High",
    internalRating: "BB",
    facilityStatus: "Pipeline",
    approvalAuthority: "Head Office",
    syndicated: false,
    applicationDate: "2026-07-20",
    approvalDate: "",
    drawdownDate: "",
    maturityDate: "2030-07-30",
    closingDate: "2026-08-15",
    nextReviewDate: "",
    stage: "Identification",
    probability: 10,
    remarks: "NNTB SME print media group requesting unsecured capex facility; KYC still pending.",
    updatedAt: "2026-06-28T11:30:00.000Z",
  },
  {
    id: "deal-4",
    name: "Morlong Trade Finance Line",
    facilityNumber: "LN-2026-004",
    accountId: "acc-4",
    account: "Morlong Associates (Sample)",
    contact: "James Venere (Sample)",
    owner: "Jenny",
    businessUnit: "Trade Finance",
    bookingBranch: "HK Admiralty Trade",
    productType: "Trade Finance",
    purpose: "Trade Finance",
    currency: "USD",
    amount: 25000000,
    approvedAmount: 22000000,
    outstandingBalance: 8500000,
    tenorMonths: 12,
    repaymentFrequency: "Bullet",
    rateType: "Fixed",
    interestRate: 5.15,
    benchmarkRate: "",
    spreadBps: 0,
    arrangementFeeBps: 20,
    commitmentFeeBps: 25,
    utilizationPct: 39,
    collateralType: "Cash Deposit",
    collateralValue: 10000000,
    ltv: 81,
    guarantor: "Morlong Group",
    riskGrade: "Low",
    internalRating: "A",
    facilityStatus: "Drawn",
    approvalAuthority: "Credit Committee",
    syndicated: true,
    applicationDate: "2026-07-10",
    approvalDate: "2026-07-25",
    drawdownDate: "2026-07-28",
    maturityDate: "2027-07-29",
    closingDate: "2026-07-29",
    nextReviewDate: "2027-01-29",
    stage: "Completion",
    probability: 100,
    remarks: "ETB corporate client; 40% club deal with two partner banks for LC/TR limits.",
    updatedAt: "2026-07-27T13:40:00.000Z",
  },
  {
    id: "deal-5",
    name: "Pacific Fleet Expansion Loan",
    facilityNumber: "LN-2026-005",
    accountId: "acc-5",
    account: "Pacific Logistics Hub",
    contact: "Lenna Paprocki (Sample)",
    owner: "Mitsu",
    businessUnit: "Commercial Banking",
    bookingBranch: "HK Kwai Chung Commercial",
    productType: "Term Loan",
    purpose: "Asset Purchase",
    currency: "HKD",
    amount: 18000000,
    approvedAmount: 0,
    outstandingBalance: 0,
    tenorMonths: 60,
    repaymentFrequency: "Monthly",
    rateType: "Floating",
    interestRate: 4.9,
    benchmarkRate: "HIBOR 3M",
    spreadBps: 140,
    arrangementFeeBps: 45,
    commitmentFeeBps: 0,
    utilizationPct: 0,
    collateralType: "Property",
    collateralValue: 28000000,
    ltv: 64,
    guarantor: "Pacific Trade Consortium",
    riskGrade: "Medium",
    internalRating: "BBB",
    facilityStatus: "Pipeline",
    approvalAuthority: "Regional Credit",
    syndicated: false,
    applicationDate: "2026-07-24",
    approvalDate: "",
    drawdownDate: "",
    maturityDate: "2031-08-05",
    closingDate: "2026-08-05",
    nextReviewDate: "2026-07-01",
    stage: "Identification",
    probability: 10,
    remarks: "Asset-backed term loan for container fleet expansion at Kwai Chung terminal.",
    updatedAt: "2026-07-05T08:15:00.000Z",
  },
  {
    id: "deal-6",
    name: "Aurora Hospital Capex Facility",
    facilityNumber: "LN-2026-006",
    accountId: "acc-6",
    account: "Aurora Health Systems",
    contact: "Leota Dilliard (Sample)",
    owner: "Leota",
    businessUnit: "Corporate Banking",
    bookingBranch: "SG Novena Corporate",
    productType: "Term Loan",
    purpose: "Property Finance",
    currency: "SGD",
    amount: 65000000,
    approvedAmount: 60000000,
    outstandingBalance: 0,
    tenorMonths: 84,
    repaymentFrequency: "Semi-annual",
    rateType: "Floating",
    interestRate: 3.95,
    benchmarkRate: "SORA 6M",
    spreadBps: 85,
    arrangementFeeBps: 30,
    commitmentFeeBps: 20,
    utilizationPct: 0,
    collateralType: "Property",
    collateralValue: 120000000,
    ltv: 50,
    guarantor: "Aurora International",
    riskGrade: "Low",
    internalRating: "A+",
    facilityStatus: "Committed",
    approvalAuthority: "Head Office",
    syndicated: true,
    applicationDate: "2026-05-12",
    approvalDate: "2026-07-08",
    drawdownDate: "",
    maturityDate: "2033-07-15",
    closingDate: "2026-07-30",
    nextReviewDate: "2027-07-15",
    stage: "Approval",
    probability: 50,
    remarks: "NTB healthcare group; facility approved pending first drawdown for Novena campus.",
    updatedAt: "2026-07-28T09:10:00.000Z",
  },
  {
    id: "deal-7",
    name: "NovaTech Overdraft Facility",
    facilityNumber: "LN-2026-007",
    accountId: "acc-7",
    account: "NovaTech Solutions",
    contact: "Donette Foller (Sample)",
    owner: "Donna",
    businessUnit: "SME Banking",
    bookingBranch: "HK Science Park SME",
    productType: "Overdraft",
    purpose: "Working Capital",
    currency: "HKD",
    amount: 3000000,
    approvedAmount: 0,
    outstandingBalance: 0,
    tenorMonths: 12,
    repaymentFrequency: "Monthly",
    rateType: "Floating",
    interestRate: 5.5,
    benchmarkRate: "HIBOR 1M",
    spreadBps: 180,
    arrangementFeeBps: 15,
    commitmentFeeBps: 40,
    utilizationPct: 0,
    collateralType: "Receivables",
    collateralValue: 4500000,
    ltv: 67,
    guarantor: "",
    riskGrade: "Medium",
    internalRating: "BB+",
    facilityStatus: "Pipeline",
    approvalAuthority: "RM Discretion",
    syndicated: false,
    applicationDate: "2026-07-01",
    approvalDate: "",
    drawdownDate: "",
    maturityDate: "2027-07-01",
    closingDate: "2026-08-20",
    nextReviewDate: "",
    stage: "Evaluation",
    probability: 25,
    remarks: "NNTB tech SME; invoice-backed OD pending KYC completion and account activation.",
    updatedAt: "2026-07-10T14:00:00.000Z",
  },
  {
    id: "deal-8",
    name: "Sterling Mortgage Portfolio",
    facilityNumber: "LN-2026-008",
    accountId: "acc-8",
    account: "Sterling Private Office",
    contact: "Simona Morasca (Sample)",
    owner: "Jenny",
    businessUnit: "Private Banking",
    bookingBranch: "London Mayfair PB",
    productType: "Mortgage",
    purpose: "Property Finance",
    currency: "USD",
    amount: 12000000,
    approvedAmount: 11000000,
    outstandingBalance: 9800000,
    tenorMonths: 120,
    repaymentFrequency: "Monthly",
    rateType: "Fixed",
    interestRate: 4.25,
    benchmarkRate: "",
    spreadBps: 0,
    arrangementFeeBps: 35,
    commitmentFeeBps: 0,
    utilizationPct: 89,
    collateralType: "Property",
    collateralValue: 18000000,
    ltv: 61,
    guarantor: "Sterling Family Trust",
    riskGrade: "Low",
    internalRating: "AA-",
    facilityStatus: "Drawn",
    approvalAuthority: "Credit Committee",
    syndicated: false,
    applicationDate: "2025-11-02",
    approvalDate: "2025-12-18",
    drawdownDate: "2026-01-15",
    maturityDate: "2036-01-15",
    closingDate: "2026-01-15",
    nextReviewDate: "2027-01-15",
    stage: "Completion",
    probability: 100,
    remarks: "ETB private banking mortgage secured on Mayfair residential portfolio.",
    updatedAt: "2026-07-29T15:05:00.000Z",
  },
];

/** Loan Facility sub-table rows, keyed by parent Loan (`deals`) id. */
export const loanFacilities: LoanFacility[] = [
  {
    id: "lf-1",
    loanId: "deal-1",
    name: "Tranche A · Working Capital",
    tranche: "A",
    currency: "HKD",
    amount: 18000000,
    status: "Drawn",
  },
  {
    id: "lf-2",
    loanId: "deal-1",
    name: "Tranche B · Capex",
    tranche: "B",
    currency: "HKD",
    amount: 8000000,
    status: "Committed",
  },
  {
    id: "lf-3",
    loanId: "deal-1",
    name: "Tranche C · Contingent",
    tranche: "C",
    currency: "HKD",
    amount: 4000000,
    status: "Pipeline",
  },
  {
    id: "lf-4",
    loanId: "deal-3",
    name: "Primary Facility",
    tranche: "A",
    currency: "USD",
    amount: 5000000,
    status: "Drawn",
  },
  {
    id: "lf-5",
    loanId: "deal-3",
    name: "Accordion Facility",
    tranche: "B",
    currency: "USD",
    amount: 2000000,
    status: "Pipeline",
  },
  {
    id: "lf-6",
    loanId: "deal-8",
    name: "Mortgage Line 1",
    tranche: "A",
    currency: "USD",
    amount: 12000000,
    status: "Drawn",
  },
];

function cloneDeal(
  base: Deal,
  patch: Partial<Deal> & Pick<Deal, "id" | "name" | "facilityNumber" | "stage" | "probability">,
): Deal {
  return { ...base, ...patch };
}

const dealSeed = deals[0];

/** Global Trade and Receivables Finance sample pipeline */
export const tradeFinanceDeals: Deal[] = [
  cloneDeal(dealSeed, {
    id: "tf-1",
    name: "Pacific Export LC Package",
    facilityNumber: "TF-2026-001",
    accountId: "acc-5",
    account: "Pacific Logistics Hub",
    contact: "Lenna Paprocki (Sample)",
    owner: "Mitsu",
    productType: "Trade Finance",
    purpose: "Trade Finance",
    currency: "USD",
    amount: 12000000,
    stage: "Identification",
    probability: 10,
    facilityStatus: "Pipeline",
    remarks: "Multi-currency LC/TR package for container export lanes.",
  }),
  cloneDeal(deals[1], {
    id: "tf-2",
    name: "Truhlar Receivables Discounting",
    facilityNumber: "TF-2026-002",
    productType: "Trade Finance",
    purpose: "Working Capital",
    currency: "SGD",
    amount: 8000000,
    stage: "Evaluation",
    probability: 25,
    remarks: "Invoice discounting against law-firm receivables.",
  }),
  cloneDeal(deals[5] ?? dealSeed, {
    id: "tf-3",
    name: "Aurora Import Documentary Credit",
    facilityNumber: "TF-2026-003",
    productType: "Trade Finance",
    purpose: "Trade Finance",
    currency: "SGD",
    amount: 15000000,
    stage: "Approval",
    probability: 50,
    remarks: "Medical equipment import LCs for hospital expansion.",
  }),
  cloneDeal(dealSeed, {
    id: "tf-4",
    name: "King Supply Chain Finance",
    facilityNumber: "TF-2026-004",
    productType: "Trade Finance",
    purpose: "Working Capital",
    currency: "HKD",
    amount: 22000000,
    stage: "Execution",
    probability: 75,
    facilityStatus: "Committed",
    remarks: "Buyer-led SCF programme for Tier-1 suppliers.",
  }),
  cloneDeal(deals[3] ?? dealSeed, {
    id: "tf-5",
    name: "Morlong Forfaiting Line",
    facilityNumber: "TF-2026-005",
    productType: "Trade Finance",
    purpose: "Trade Finance",
    currency: "USD",
    amount: 18000000,
    stage: "Completion",
    probability: 100,
    facilityStatus: "Drawn",
    remarks: "Completed forfaiting line for ASEAN trade corridors.",
  }),
];

/** Global Payment Service sample pipeline */
export const paymentServiceDeals: Deal[] = [
  cloneDeal(dealSeed, {
    id: "ps-1",
    name: "King Cross-Border Payments Mandate",
    facilityNumber: "PS-2026-001",
    productType: "Revolving Credit",
    purpose: "Working Capital",
    currency: "HKD",
    amount: 5000000,
    stage: "Identification",
    probability: 10,
    facilityStatus: "Pipeline",
    remarks: "Treasury mandate for multi-currency payment rails.",
  }),
  cloneDeal(deals[1], {
    id: "ps-2",
    name: "Truhlar Payroll & Collections Hub",
    facilityNumber: "PS-2026-002",
    currency: "SGD",
    amount: 2500000,
    stage: "Evaluation",
    probability: 25,
    remarks: "Evaluation of virtual account and collections stack.",
  }),
  cloneDeal(deals[3] ?? dealSeed, {
    id: "ps-3",
    name: "Morlong Global Pay Live",
    facilityNumber: "PS-2026-003",
    currency: "USD",
    amount: 9000000,
    stage: "Completion",
    probability: 100,
    facilityStatus: "Drawn",
    remarks: "Live payment hub covering HKD/USD/SGD corridors.",
  }),
];

/** Sustainable Finance sample pipeline */
export const sustainableFinanceDeals: Deal[] = [
  cloneDeal(dealSeed, {
    id: "sf-1",
    name: "Pacific Green Capex Facility",
    facilityNumber: "SF-2026-001",
    accountId: "acc-5",
    account: "Pacific Logistics Hub",
    owner: "Mitsu",
    productType: "Term Loan",
    purpose: "Asset Purchase",
    currency: "HKD",
    amount: 28000000,
    stage: "Identification",
    probability: 10,
    remarks: "Green term loan for electric fleet conversion.",
  }),
  cloneDeal(deals[5] ?? dealSeed, {
    id: "sf-2",
    name: "Aurora Sustainability-Linked RCF",
    facilityNumber: "SF-2026-002",
    productType: "Revolving Credit",
    purpose: "Working Capital",
    currency: "SGD",
    amount: 40000000,
    stage: "Evaluation",
    probability: 25,
    remarks: "SLRCF with KPI-linked margin ratchet.",
  }),
  cloneDeal(deals[1], {
    id: "sf-3",
    name: "Truhlar Green Bond Advisory",
    facilityNumber: "SF-2026-003",
    currency: "SGD",
    amount: 15000000,
    stage: "Approval",
    probability: 50,
    remarks: "Credit approval pending for green use-of-proceeds framework.",
  }),
  cloneDeal(deals[7] ?? dealSeed, {
    id: "sf-4",
    name: "Sterling ESG Mortgage Pool",
    facilityNumber: "SF-2026-004",
    productType: "Mortgage",
    purpose: "Property Finance",
    currency: "HKD",
    amount: 35000000,
    stage: "Completion",
    probability: 100,
    facilityStatus: "Drawn",
    remarks: "Completed green residential mortgage pool.",
  }),
];

/** Global Market sample pipeline */
export const globalMarketDeals: Deal[] = [
  cloneDeal(dealSeed, {
    id: "gm-1",
    name: "King FX Hedging Programme",
    facilityNumber: "GM-2026-001",
    productType: "Revolving Credit",
    purpose: "Other",
    currency: "USD",
    amount: 20000000,
    stage: "Identification",
    probability: 10,
    remarks: "FX options overlay for export receivables.",
  }),
  cloneDeal(deals[1], {
    id: "gm-2",
    name: "Truhlar Interest Rate Swap",
    facilityNumber: "GM-2026-002",
    currency: "SGD",
    amount: 10000000,
    stage: "Evaluation",
    probability: 25,
    remarks: "Pay-fixed IRS against floating RCF.",
  }),
  cloneDeal(deals[5] ?? dealSeed, {
    id: "gm-3",
    name: "Aurora Bond Issuance Support",
    facilityNumber: "GM-2026-003",
    currency: "SGD",
    amount: 80000000,
    stage: "Approval",
    probability: 50,
    remarks: "DCM support for hospital group MTN tranche.",
  }),
  cloneDeal(dealSeed, {
    id: "gm-4",
    name: "King Structured Notes Placement",
    facilityNumber: "GM-2026-004",
    currency: "HKD",
    amount: 45000000,
    stage: "Execution",
    probability: 75,
    facilityStatus: "Committed",
    remarks: "Execution of structured note bookbuild.",
  }),
  cloneDeal(deals[3] ?? dealSeed, {
    id: "gm-5",
    name: "Morlong Commodity Hedge Book",
    facilityNumber: "GM-2026-005",
    currency: "USD",
    amount: 30000000,
    stage: "Completion",
    probability: 100,
    facilityStatus: "Drawn",
    remarks: "Completed commodity hedge programme for trade book.",
  }),
];

/** Life Insurance sample pipeline */
export const lifeInsuranceDeals: Deal[] = [
  cloneDeal(deals[7] ?? dealSeed, {
    id: "li-1",
    name: "Sterling Family Protection Plan",
    facilityNumber: "LI-2026-001",
    productType: "Term Loan",
    purpose: "Other",
    currency: "HKD",
    amount: 8000000,
    stage: "Identification",
    probability: 10,
    facilityStatus: "Pipeline",
    remarks: "High-net-worth whole life needs analysis.",
  }),
  cloneDeal(deals[1], {
    id: "li-2",
    name: "Truhlar Keyman Cover Review",
    facilityNumber: "LI-2026-002",
    currency: "SGD",
    amount: 3500000,
    stage: "Evaluation",
    probability: 25,
    remarks: "Partnership keyman life cover underwriting.",
  }),
  cloneDeal(dealSeed, {
    id: "li-3",
    name: "King Group Endowment Closed",
    facilityNumber: "LI-2026-003",
    currency: "HKD",
    amount: 12000000,
    stage: "Completion",
    probability: 100,
    facilityStatus: "Drawn",
    remarks: "Group endowment placement completed for executives.",
  }),
];

export const productPipelineData = {
  deals,
  tradeFinance: tradeFinanceDeals,
  paymentService: paymentServiceDeals,
  sustainableFinance: sustainableFinanceDeals,
  globalMarket: globalMarketDeals,
  lifeInsurance: lifeInsuranceDeals,
} as const;

export const campaigns: Campaign[] = [
  {
    id: "camp-1",
    name: "Q3 Working Capital Drive",
    code: "CMP-2026-001",
    owner: "Jenny",
    type: "Client Acquisition",
    status: "Active",
    channel: "Mixed",
    businessUnit: "Corporate Banking",
    targetSegment: "Corporate",
    targetRegion: "Hong Kong",
    targetProduct: "Term Loan",
    currency: "HKD",
    startDate: "2026-07-01",
    endDate: "2026-09-30",
    expectedRevenue: 120000000,
    budgetedCost: 850000,
    actualCost: 420000,
    expectedResponsePct: 8,
    numSent: 2400,
    leadsGenerated: 186,
    convertedCount: 24,
    description: "Outbound campaign targeting mid-market corporates for short-tenor working capital facilities.",
  },
  {
    id: "camp-2",
    name: "Trade Finance Webinar Series",
    code: "CMP-2026-002",
    owner: "Jenny",
    type: "Event / Seminar",
    status: "Planning",
    channel: "Webinar",
    businessUnit: "Trade Finance",
    targetSegment: "Commercial",
    targetRegion: "Asia Pacific",
    targetProduct: "Trade Finance",
    currency: "USD",
    startDate: "2026-08-15",
    endDate: "2026-10-15",
    expectedRevenue: 45000000,
    budgetedCost: 180000,
    actualCost: 35000,
    expectedResponsePct: 12,
    numSent: 980,
    leadsGenerated: 0,
    convertedCount: 0,
    description: "Three-part webinar series on LC / supply-chain finance for commercial importers and exporters.",
  },
  {
    id: "camp-3",
    name: "SME Revolving Credit Cross-Sell",
    code: "CMP-2026-003",
    owner: "Alex",
    type: "Cross-Sell / Upsell",
    status: "Active",
    channel: "Email",
    businessUnit: "SME Banking",
    targetSegment: "SME",
    targetRegion: "Hong Kong",
    targetProduct: "Revolving Credit",
    currency: "HKD",
    startDate: "2026-06-01",
    endDate: "2026-08-31",
    expectedRevenue: 28000000,
    budgetedCost: 120000,
    actualCost: 98000,
    expectedResponsePct: 6,
    numSent: 5600,
    leadsGenerated: 312,
    convertedCount: 41,
    description: "Email nurture for ETB SME clients with existing OD looking to upgrade to committed RCF.",
  },
  {
    id: "camp-4",
    name: "Private Banking Mortgage Roadshow",
    code: "CMP-2025-018",
    owner: "Jenny",
    type: "Conference",
    status: "Completed",
    channel: "In-Person Event",
    businessUnit: "Private Banking",
    targetSegment: "Private Banking",
    targetRegion: "Hong Kong",
    targetProduct: "Mortgage",
    currency: "HKD",
    startDate: "2026-03-01",
    endDate: "2026-03-20",
    expectedRevenue: 90000000,
    budgetedCost: 650000,
    actualCost: 612000,
    expectedResponsePct: 15,
    numSent: 420,
    leadsGenerated: 68,
    convertedCount: 11,
    description: "Invitation-only roadshow for HNW clients on UK / HK residential mortgage facilities.",
  },
  {
    id: "camp-5",
    name: "Partner Referral — Accounting Firms",
    code: "CMP-2026-004",
    owner: "Alex",
    type: "Partner Referral",
    status: "Inactive",
    channel: "Partner",
    businessUnit: "Commercial Banking",
    targetSegment: "Commercial",
    targetRegion: "Singapore",
    targetProduct: "Overdraft",
    currency: "SGD",
    startDate: "2026-01-15",
    endDate: "2026-06-30",
    expectedRevenue: 15000000,
    budgetedCost: 95000,
    actualCost: 72000,
    expectedResponsePct: 10,
    numSent: 65,
    leadsGenerated: 22,
    convertedCount: 5,
    description: "Referral partnership with mid-tier accounting firms introducing commercial OD prospects.",
  },
];

export const timeline: TimelineEvent[] = [
  { id: "tl-1", time: "03:36 PM", title: "Lead Created", detail: "by Jenny 2026-07-28" },
  { id: "tl-2", time: "03:36 PM", title: "Note added", detail: "yrqwiorywqior by Jenny" },
  { id: "tl-3", time: "03:36 PM", title: "Note updated", detail: "yrqwiorywqiorfsahk by Jenny" },
  { id: "tl-4", time: "03:36 PM", title: "Note deleted", detail: "yrqwiorywqiorfsahk by Jenny" },
];

export const workflowRules: WorkflowRule[] = [
  {
    name: "Deal discount approval",
    module: "Loans",
    condition: "Amount exceeds configured threshold",
    action: "Create manager approval task",
  },
  {
    name: "New lead follow-up",
    module: "Leads",
    condition: "Lead is created from campaign",
    action: "Assign owner and create task",
  },
];

export const systemFilters = ["Record Action", "Related Records Action", "Touched Records", "Untouched Records"];

export const leadFilters = ["Activities", "Campaigns", "Latest Email Status", "Address", "Address - City", "Address - Country / Region"];

export const taskFilters = ["Closed Time", "Contact Name", "Created By", "Created Time", "Due Date", "Last Activity Time", "Modified By", "Modified Time"];

export const callFilters = ["Call Agenda", "Call Duration", "Call Duration in seconds", "Call Owner", "Call Purpose", "Call Result", "Call Start Time"];
